export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILURE";

export const GET_HISTORY = "GET_HISTORY";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAILED = "GET_HISTORY_FAILED";

export const ADD_ITEM = "ADD_ITEM";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAILED = "ADD_ITEM_FAILED";

export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAILED = "UPDATE_ITEM_FAILED";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const ADD_VENDOR = "ADD_VENDOR";
export const ADD_VENDOR_SUCCESS = "ADD_VENDOR_SUCCESS";
export const ADD_VENDOR_FAILED = "ADD_VENDOR_FAILED";

export const GET_CATEGORY_ITEMS = "GET_CATEGORY_ITEMS";
export const INIT_STATE = "INIT_STATE";

export const SET_SEARCH_MODE = "SET_SEARCH_MODE";
export const REMOVE_SEARCH_MODE = "REMOVE_SEARCH_MODE";

export const ADD_LINK = "ADD_LINK";
export const REMOVE_LINK = "REMOVE_LINK";
export const SET_ERROR = "REMOVE_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const UPDATE_IMAGE_SUCCESS = "UPDATE_IMAGE_SUCCESS";
export const UPDATE_IMAGE_FAILED = "UPDATE_IMAGE_FAILED";

export const UPDATE_ITEM_QUANTITY = "UPDATE_ITEM_QUANTITY";
